import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  requirementsSidebar: [{ type: "autogenerated", dirName: "Requirements" }],
  designSidebar: [{ type: "autogenerated", dirName: "Implementation" }],
  implementationSidebar: [{ type: "autogenerated", dirName: "Implementation" }],
  userSidebar: [{ type: "autogenerated", dirName: "User" }],
  testingSidebar: [{ type: "autogenerated", dirName: "Testing" }],
  projectManagementSidebar: [
    { type: "autogenerated", dirName: "ProjectManagement" },
  ],
};

export default sidebars;
