import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  requirementsSidebar: [{ type: "autogenerated", dirName: "Requirements" }],
  designSidebar: [
    {
      type: "category",
      label: "Design",
      items: [
        "Design/index",
        {
          type: "category",
          label: "Introduction",
          items: [
            "Design/Introduction/Glossary",
            "Design/Introduction/OverviewOfDocument",
            "Design/Introduction/Purpose",
            "Design/Introduction/References",
            "Design/Introduction/ScopeOfProject",
          ],
        },
        {
          type: "category",
          label: "Overall Description",
          items: [
            "Design/OverallDescription/SystemEnvironment",
            {
              type: "category",
              label: "Functional Requirements Specification",
              items: [
                "Design/OverallDescription/FunctionalRequirementsSpecification/index",
                {
                  type: "category",
                  label: "General",
                  items: [
                    "Design/OverallDescription/FunctionalRequirementsSpecification/General/Index",
                  ],
                },
                {
                  type: "category",
                  label: "EDR",
                  items: [
                    "Design/OverallDescription/FunctionalRequirementsSpecification/EDR/Index",
                    "Design/OverallDescription/FunctionalRequirementsSpecification/EDR/DispatcherUseCase1",
                    "Design/OverallDescription/FunctionalRequirementsSpecification/EDR/DispatcherUseCase2",
                    "Design/OverallDescription/FunctionalRequirementsSpecification/EDR/DispatcherUseCase3",
                    "Design/OverallDescription/FunctionalRequirementsSpecification/EDR/DispatcherUseCase4",
                    "Design/OverallDescription/FunctionalRequirementsSpecification/EDR/TrainerUseCase1",
                    "Design/OverallDescription/FunctionalRequirementsSpecification/EDR/TrainerUseCase2",
                    "Design/OverallDescription/FunctionalRequirementsSpecification/EDR/TrainerUseCase3",
                    "Design/OverallDescription/FunctionalRequirementsSpecification/EDR/TrainerUseCase4",
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  implementationSidebar: [{ type: "autogenerated", dirName: "Implementation" }],
  userSidebar: [{ type: "autogenerated", dirName: "User" }],
  testingSidebar: [{ type: "autogenerated", dirName: "Testing" }],
  projectManagementSidebar: [
    { type: "autogenerated", dirName: "ProjectManagement" },
  ],
};

export default sidebars;
